export interface Currency {
  code: string;
  name: string;
  flag: string;
  color: string;
}

export const CURRENCIES: Currency[] = [
  { code: 'USD', name: 'US Dollar', flag: '🇺🇸', color: '#0A3161' },
  { code: 'EUR', name: 'Euro', flag: '🇪🇺', color: '#003399' },
  { code: 'GBP', name: 'British Pound', flag: '🇬🇧', color: '#C8102E' },
  { code: 'JPY', name: 'Japanese Yen', flag: '🇯🇵', color: '#BC002D' },
  { code: 'AUD', name: 'Australian Dollar', flag: '🇦🇺', color: '#FFCD00' },
  { code: 'CAD', name: 'Canadian Dollar', flag: '🇨🇦', color: '#D80621' },
  { code: 'CHF', name: 'Swiss Franc', flag: '🇨🇭', color: '#D52B1E' },
  { code: 'CNY', name: 'Chinese Yuan', flag: '🇨🇳', color: '#EE1C25' },
  { code: 'INR', name: 'Indian Rupee', flag: '🇮🇳', color: '#FF9933' },
  { code: 'NZD', name: 'New Zealand Dollar', flag: '🇳🇿', color: '#00247D' },
  { code: 'BRL', name: 'Brazilian Real', flag: '🇧🇷', color: '#009739' },
  { code: 'RUB', name: 'Russian Ruble', flag: '🇷🇺', color: '#0039A6' },
  { code: 'KRW', name: 'South Korean Won', flag: '🇰🇷', color: '#0047A0' },
  { code: 'SGD', name: 'Singapore Dollar', flag: '🇸🇬', color: '#EF3340' },
  { code: 'MXN', name: 'Mexican Peso', flag: '🇲🇽', color: '#006341' },
  { code: 'HKD', name: 'Hong Kong Dollar', flag: '🇭🇰', color: '#ED1C24' },
  { code: 'SEK', name: 'Swedish Krona', flag: '🇸🇪', color: '#006AA7' },
  { code: 'NOK', name: 'Norwegian Krone', flag: '🇳🇴', color: '#EF3340' },
  { code: 'TRY', name: 'Turkish Lira', flag: '🇹🇷', color: '#E30A17' },
  { code: 'IDR', name: 'Indonesian Rupiah', flag: '🇮🇩', color: '#FF0000' },
  { code: 'THB', name: 'Thai Baht', flag: '🇹🇭', color: '#2D2A4A' },
  { code: 'MYR', name: 'Malaysian Ringgit', flag: '🇲🇾', color: '#003366' },
  { code: 'PHP', name: 'Philippine Peso', flag: '🇵🇭', color: '#0038A8' },
  { code: 'VND', name: 'Vietnamese Dong', flag: '🇻🇳', color: '#DA251D' },
  { code: 'ZAR', name: 'South African Rand', flag: '🇿🇦', color: '#007A33' },
  { code: 'DKK', name: 'Danish Krone', flag: '🇩🇰', color: '#C8102E' },
  { code: 'PLN', name: 'Polish Zloty', flag: '🇵🇱', color: '#DC143C' },
  { code: 'TWD', name: 'New Taiwan Dollar', flag: '🇹🇼', color: '#FE0000' },
  { code: 'AED', name: 'UAE Dirham', flag: '🇦🇪', color: '#00732F' },
  { code: 'AFN', name: 'Afghan Afghani', flag: '🇦🇫', color: '#000000' },
  { code: 'ALL', name: 'Albanian Lek', flag: '🇦🇱', color: '#ED1C24' },
  { code: 'AMD', name: 'Armenian Dram', flag: '🇦🇲', color: '#FF4F00' },
  { code: 'ANG', name: 'Netherlands Antillean Guilder', flag: '🇳🇱', color: '#AE1C28' },
  { code: 'AOA', name: 'Angolan Kwanza', flag: '🇦🇴', color: '#CE1126' },
  { code: 'ARS', name: 'Argentine Peso', flag: '🇦🇷', color: '#74ACDF' },
  { code: 'AWG', name: 'Aruban Florin', flag: '🇦🇼', color: '#4189DD' },
  { code: 'AZN', name: 'Azerbaijani Manat', flag: '🇦🇿', color: '#00B5E2' },
  { code: 'BAM', name: 'Bosnia and Herzegovina Convertible Mark', flag: '🇧🇦', color: '#002395' },
  { code: 'BBD', name: 'Barbadian Dollar', flag: '🇧🇧', color: '#00267F' },
  { code: 'BDT', name: 'Bangladeshi Taka', flag: '🇧🇩', color: '#006A4E' },
  { code: 'BGN', name: 'Bulgarian Lev', flag: '🇧🇬', color: '#00966E' },
  { code: 'BHD', name: 'Bahraini Dinar', flag: '🇧🇭', color: '#CE1126' },
  { code: 'BIF', name: 'Burundian Franc', flag: '🇧🇮', color: '#CE1126' },
  { code: 'BMD', name: 'Bermudian Dollar', flag: '🇧🇲', color: '#BF1E2D' },
  { code: 'BND', name: 'Brunei Dollar', flag: '🇧🇳', color: '#F7E100' },
  { code: 'BOB', name: 'Bolivian Boliviano', flag: '🇧🇴', color: '#007934' },
  { code: 'BSD', name: 'Bahamian Dollar', flag: '🇧🇸', color: '#00778B' },
  { code: 'BTN', name: 'Bhutanese Ngultrum', flag: '🇧🇹', color: '#FF4E12' },
  { code: 'BWP', name: 'Botswana Pula', flag: '🇧🇼', color: '#00CBFF' },
  { code: 'BYN', name: 'Belarusian Ruble', flag: '🇧🇾', color: '#C8102E' },
  { code: 'BZD', name: 'Belize Dollar', flag: '🇧🇿', color: '#003F87' },
  { code: 'CLP', name: 'Chilean Peso', flag: '🇨🇱', color: '#0039A6' },
  { code: 'COP', name: 'Colombian Peso', flag: '🇨🇴', color: '#FCD116' },
  { code: 'CRC', name: 'Costa Rican Colon', flag: '🇨🇷', color: '#002B7F' },
  { code: 'CUP', name: 'Cuban Peso', flag: '🇨🇺', color: '#002A8F' },
  { code: 'CVE', name: 'Cape Verdean Escudo', flag: '🇨🇻', color: '#003893' },
  { code: 'CZK', name: 'Czech Koruna', flag: '🇨🇿', color: '#11457E' },
  { code: 'DJF', name: 'Djiboutian Franc', flag: '🇩🇯', color: '#6AB2E7' },
  { code: 'DOP', name: 'Dominican Peso', flag: '🇩🇴', color: '#002D62' },
  { code: 'DZD', name: 'Algerian Dinar', flag: '🇩🇿', color: '#006233' },
  { code: 'EGP', name: 'Egyptian Pound', flag: '🇪🇬', color: '#C09307' },
  { code: 'ERN', name: 'Eritrean Nakfa', flag: '🇪🇷', color: '#00AD11' },
  { code: 'ETB', name: 'Ethiopian Birr', flag: '🇪🇹', color: '#006233' },
  { code: 'FJD', name: 'Fijian Dollar', flag: '🇫🇯', color: '#62B5E5' },
  { code: 'FKP', name: 'Falkland Islands Pound', flag: '🇫🇰', color: '#002147' },
  { code: 'GEL', name: 'Georgian Lari', flag: '🇬🇪', color: '#FF0000' },
  { code: 'GGP', name: 'Guernsey Pound', flag: '🇬🇬', color: '#E8112D' },
  { code: 'GHS', name: 'Ghanaian Cedi', flag: '🇬🇭', color: '#006B3F' },
  { code: 'GIP', name: 'Gibraltar Pound', flag: '🇬🇮', color: '#CE1126' },
  { code: 'GMD', name: 'Gambian Dalasi', flag: '🇬🇲', color: '#3A7728' },
  { code: 'GNF', name: 'Guinean Franc', flag: '🇬🇳', color: '#CE1126' },
  { code: 'GTQ', name: 'Guatemalan Quetzal', flag: '🇬🇹', color: '#4997D0' },
  { code: 'GYD', name: 'Guyanese Dollar', flag: '🇬🇾', color: '#009E49' },
  { code: 'HNL', name: 'Honduran Lempira', flag: '🇭🇳', color: '#0073CF' },
  { code: 'HRK', name: 'Croatian Kuna', flag: '🇭🇷', color: '#000000' },
  { code: 'HTG', name: 'Haitian Gourde', flag: '🇭🇹', color: '#CE1126' },
  { code: 'HUF', name: 'Hungarian Forint', flag: '🇭🇺', color: '#436F4D' },
  { code: 'ILS', name: 'Israeli New Shekel', flag: '🇮🇱', color: '#0038B8' },
  { code: 'IMP', name: 'Isle of Man Pound', flag: '🇮🇲', color: '#CE1126' },
  { code: 'IQD', name: 'Iraqi Dinar', flag: '🇮🇶', color: '#007A33' },
  { code: 'IRR', name: 'Iranian Rial', flag: '🇮🇷', color: '#239F40' },
  { code: 'ISK', name: 'Icelandic Krona', flag: '🇮🇸', color: '#003897' },
  { code: 'JMD', name: 'Jamaican Dollar', flag: '🇯🇲', color: '#009B3A' },
  { code: 'KES', name: 'Kenyan Shilling', flag: '🇰🇪', color: '#BB0000' },
  { code: 'KMF', name: 'Comorian Franc', flag: '🇰🇲', color: '#3D3C3A' },
];

export const getCurrencyByCode = (code: string): Currency => {
  return CURRENCIES.find((c) => c.code === code) || CURRENCIES[0];
};
