export interface Currency {
  code: string;
  name: string;
  countryCode: string;
  color: string;
}

export const CURRENCIES: Currency[] = [
  { code: 'USD', name: 'US Dollar', countryCode: 'US', color: '#0A3161' },
  { code: 'EUR', name: 'Euro', countryCode: 'EU', color: '#003399' },
  { code: 'GBP', name: 'British Pound', countryCode: 'GB', color: '#C8102E' },
  { code: 'JPY', name: 'Japanese Yen', countryCode: 'JP', color: '#BC002D' },
  { code: 'AUD', name: 'Australian Dollar', countryCode: 'AU', color: '#FFCD00' },
  { code: 'CAD', name: 'Canadian Dollar', countryCode: 'CA', color: '#D80621' },
  { code: 'CHF', name: 'Swiss Franc', countryCode: 'CH', color: '#D52B1E' },
  { code: 'CNY', name: 'Chinese Yuan', countryCode: 'CN', color: '#EE1C25' },
  { code: 'INR', name: 'Indian Rupee', countryCode: 'IN', color: '#FF9933' },
  { code: 'NZD', name: 'New Zealand Dollar', countryCode: 'NZ', color: '#00247D' },
  { code: 'BRL', name: 'Brazilian Real', countryCode: 'BR', color: '#009739' },
  { code: 'RUB', name: 'Russian Ruble', countryCode: 'RU', color: '#0039A6' },
  { code: 'KRW', name: 'South Korean Won', countryCode: 'KR', color: '#0047A0' },
  { code: 'SGD', name: 'Singapore Dollar', countryCode: 'SG', color: '#EF3340' },
  { code: 'MXN', name: 'Mexican Peso', countryCode: 'MX', color: '#006341' },
  { code: 'HKD', name: 'Hong Kong Dollar', countryCode: 'HK', color: '#ED1C24' },
  { code: 'SEK', name: 'Swedish Krona', countryCode: 'SE', color: '#006AA7' },
  { code: 'NOK', name: 'Norwegian Krone', countryCode: 'NO', color: '#EF3340' },
  { code: 'TRY', name: 'Turkish Lira', countryCode: 'TR', color: '#E30A17' },
  { code: 'IDR', name: 'Indonesian Rupiah', countryCode: 'ID', color: '#FF0000' },
  { code: 'THB', name: 'Thai Baht', countryCode: 'TH', color: '#2D2A4A' },
  { code: 'MYR', name: 'Malaysian Ringgit', countryCode: 'MY', color: '#003366' },
  { code: 'PHP', name: 'Philippine Peso', countryCode: 'PH', color: '#0038A8' },
  { code: 'VND', name: 'Vietnamese Dong', countryCode: 'VN', color: '#DA251D' },
  { code: 'ZAR', name: 'South African Rand', countryCode: 'ZA', color: '#007A33' },
  { code: 'DKK', name: 'Danish Krone', countryCode: 'DK', color: '#C8102E' },
  { code: 'PLN', name: 'Polish Zloty', countryCode: 'PL', color: '#DC143C' },
  { code: 'TWD', name: 'New Taiwan Dollar', countryCode: 'TW', color: '#FE0000' },
  { code: 'AED', name: 'UAE Dirham', countryCode: 'AE', color: '#00732F' },
  { code: 'AFN', name: 'Afghan Afghani', countryCode: 'AF', color: '#000000' },
  { code: 'ALL', name: 'Albanian Lek', countryCode: 'AL', color: '#ED1C24' },
  { code: 'AMD', name: 'Armenian Dram', countryCode: 'AM', color: '#FF4F00' },
  { code: 'ANG', name: 'Netherlands Antillean Guilder', countryCode: 'AN', color: '#AE1C28' },
  { code: 'AOA', name: 'Angolan Kwanza', countryCode: 'AO', color: '#CE1126' },
  { code: 'ARS', name: 'Argentine Peso', countryCode: 'AR', color: '#74ACDF' },
  { code: 'AWG', name: 'Aruban Florin', countryCode: 'AW', color: '#4189DD' },
  { code: 'AZN', name: 'Azerbaijani Manat', countryCode: 'AZ', color: '#00B5E2' },
  { code: 'BAM', name: 'Bosnia and Herzegovina Convertible Mark', countryCode: 'BA', color: '#002395' },
  { code: 'BBD', name: 'Barbadian Dollar', countryCode: 'BB', color: '#00267F' },
  { code: 'BDT', name: 'Bangladeshi Taka', countryCode: 'BD', color: '#006A4E' },
  { code: 'BGN', name: 'Bulgarian Lev', countryCode: 'BG', color: '#00966E' },
  { code: 'BHD', name: 'Bahraini Dinar', countryCode: 'BH', color: '#CE1126' },
  { code: 'BIF', name: 'Burundian Franc', countryCode: 'BI', color: '#CE1126' },
  { code: 'BMD', name: 'Bermudian Dollar', countryCode: 'BM', color: '#BF1E2D' },
  { code: 'BND', name: 'Brunei Dollar', countryCode: 'BN', color: '#F7E100' },
  { code: 'BOB', name: 'Bolivian Boliviano', countryCode: 'BO', color: '#007934' },
  { code: 'BSD', name: 'Bahamian Dollar', countryCode: 'BS', color: '#00778B' },
  { code: 'BTN', name: 'Bhutanese Ngultrum', countryCode: 'BT', color: '#FF4E12' },
  { code: 'BWP', name: 'Botswana Pula', countryCode: 'BW', color: '#00CBFF' },
  { code: 'BYN', name: 'Belarusian Ruble', countryCode: 'BY', color: '#C8102E' },
  { code: 'BZD', name: 'Belize Dollar', countryCode: 'BZ', color: '#003F87' },
  { code: 'CLP', name: 'Chilean Peso', countryCode: 'CL', color: '#0039A6' },
  { code: 'COP', name: 'Colombian Peso', countryCode: 'CO', color: '#FCD116' },
  { code: 'CRC', name: 'Costa Rican Colon', countryCode: 'CR', color: '#002B7F' },
  { code: 'CUP', name: 'Cuban Peso', countryCode: 'CU', color: '#002A8F' },
  { code: 'CVE', name: 'Cape Verdean Escudo', countryCode: 'CV', color: '#003893' },
  { code: 'CZK', name: 'Czech Koruna', countryCode: 'CZ', color: '#11457E' },
  { code: 'DJF', name: 'Djiboutian Franc', countryCode: 'DJ', color: '#6AB2E7' },
  { code: 'DOP', name: 'Dominican Peso', countryCode: 'DO', color: '#002D62' },
  { code: 'DZD', name: 'Algerian Dinar', countryCode: 'DZ', color: '#006233' },
  { code: 'EGP', name: 'Egyptian Pound', countryCode: 'EG', color: '#C09307' },
  { code: 'ERN', name: 'Eritrean Nakfa', countryCode: 'ER', color: '#00AD11' },
  { code: 'ETB', name: 'Ethiopian Birr', countryCode: 'ET', color: '#006233' },
  { code: 'FJD', name: 'Fijian Dollar', countryCode: 'FJ', color: '#62B5E5' },
  { code: 'FKP', name: 'Falkland Islands Pound', countryCode: 'FK', color: '#002147' },
  { code: 'GEL', name: 'Georgian Lari', countryCode: 'GE', color: '#FF0000' },
  { code: 'GGP', name: 'Guernsey Pound', countryCode: 'GG', color: '#E8112D' },
  { code: 'GHS', name: 'Ghanaian Cedi', countryCode: 'GH', color: '#006B3F' },
  { code: 'GIP', name: 'Gibraltar Pound', countryCode: 'GI', color: '#CE1126' },
  { code: 'GMD', name: 'Gambian Dalasi', countryCode: 'GM', color: '#3A7728' },
  { code: 'GNF', name: 'Guinean Franc', countryCode: 'GN', color: '#CE1126' },
  { code: 'GTQ', name: 'Guatemalan Quetzal', countryCode: 'GT', color: '#4997D0' },
  { code: 'GYD', name: 'Guyanese Dollar', countryCode: 'GY', color: '#009E49' },
  { code: 'HNL', name: 'Honduran Lempira', countryCode: 'HN', color: '#0073CF' },
  { code: 'HRK', name: 'Croatian Kuna', countryCode: 'HR', color: '#000000' },
  { code: 'HTG', name: 'Haitian Gourde', countryCode: 'HT', color: '#CE1126' },
  { code: 'HUF', name: 'Hungarian Forint', countryCode: 'HU', color: '#436F4D' },
  { code: 'ILS', name: 'Israeli New Shekel', countryCode: 'IL', color: '#0038B8' },
  { code: 'IMP', name: 'Isle of Man Pound', countryCode: 'IM', color: '#CE1126' },
  { code: 'IQD', name: 'Iraqi Dinar', countryCode: 'IQ', color: '#007A33' },
  { code: 'IRR', name: 'Iranian Rial', countryCode: 'IR', color: '#239F40' },
  { code: 'ISK', name: 'Icelandic Krona', countryCode: 'IS', color: '#003897' },
  { code: 'JMD', name: 'Jamaican Dollar', countryCode: 'JM', color: '#009B3A' },
  { code: 'KES', name: 'Kenyan Shilling', countryCode: 'KE', color: '#BB0000' },
  { code: 'KMF', name: 'Comorian Franc', countryCode: 'KM', color: '#3D3C3A' },
];

export const getCurrencyByCode = (code: string): Currency => {
  return CURRENCIES.find((c) => c.code === code) || CURRENCIES[0];
};

export const getFlagUrl = (countryCode: string) => {
  return `https://flagcdn.com/w160/${countryCode.toLowerCase()}.png`;
};
